# Generated by Django 4.1.13 on 2024-08-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountModule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='تایید شده/ نشده'),
        ),
    ]
